#!/bin/sh

# this is a script which avoids having to install intltool just to
# translate three phrases

# to add a translation - add the language to LINGUAS, copy
# chatstatus.pot to a po file for the language, and then run this script

for file in `ls *.po | sed -e 's/.po//g'`
do

if ! [ -d ../locale/$file/LC_MESSAGES ]; then
  mkdir -p ../locale/$file/LC_MESSAGES
fi

msgfmt $file.po
mv messages.mo ../locale/$file/LC_MESSAGES/chatstatus.mo

done
